backend/config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :pixels do
    post :create_bulk, on: :collection
  end

  resource :session, only: [:new, :create, :destroy] do
    post :callback
  end

  resource :registration, only: [:new, :create] do
    post :callback
  end

  resources :credentials, only: [:create, :destroy] do
    post :callback, on: :collection
  end

  # post "session_callback", to: "sessions#callback"
  # post "registration_callback", to: "registrations#callback"
  root to: "home#index"
end

backend/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/credential.rb
# frozen_string_literal: true

class Credential < ApplicationRecord
  validates :external_id, :public_key, :nickname, :sign_count, presence: true
  validates :external_id, uniqueness: true
  validates :sign_count,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2**32 - 1 }
end

backend/app/models/pixel.rb
class Pixel < ApplicationRecord
  belongs_to :user
end

backend/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  CREDENTIAL_MIN_AMOUNT = 1

  has_many :credentials, dependent: :destroy
  has_many :pixels, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  after_initialize do
    self.webauthn_id ||= WebAuthn.generate_user_id
  end

  def can_delete_credentials?
    credentials.size > CREDENTIAL_MIN_AMOUNT
  end
end

backend/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  skip_before_action :verify_authenticity_token

  private

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def current_user
    @current_user ||=
      if session[:user_id]
        User.find_by(id: session[:user_id])
      end
  end
end

backend/app/controllers/credentials_controller.rb
# frozen_string_literal: true

class CredentialsController < ApplicationController
  def create
    create_options = WebAuthn::Credential.options_for_create(
      user: {
        id: current_user.webauthn_id,
        name: current_user.username,
      },
      exclude: current_user.credentials.pluck(:external_id),
      authenticator_selection: { user_verification: "required" }
    )

    session[:current_registration] = { challenge: create_options.challenge }

    respond_to do |format|
      format.json { render json: create_options }
    end
  end

  def callback
    webauthn_credential = WebAuthn::Credential.from_create(params)

    begin
      webauthn_credential.verify(session["current_registration"]["challenge"], user_verification: true)

      credential = current_user.credentials.find_or_initialize_by(
        external_id: Base64.strict_encode64(webauthn_credential.raw_id)
      )

      if credential.update(
        nickname: params[:credential_nickname],
        public_key: webauthn_credential.public_key,
        sign_count: webauthn_credential.sign_count
      )
        render json: { status: "ok" }, status: :ok
      else
        render json: "Couldn't add your Security Key", status: :unprocessable_entity
      end
    rescue WebAuthn::Error => e
      render json: "Verification failed: #{e.message}", status: :unprocessable_entity
    ensure
      session.delete("current_registration")
    end
  end

  def destroy
    if current_user&.can_delete_credentials?
      current_user.credentials.destroy(params[:id])
    end

    redirect_to root_path
  end
end

backend/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :enforce_current_user

  def index
  end

  private

  def enforce_current_user
    if current_user.blank?
      redirect_to new_session_path
    end
  end
end

backend/app/controllers/pixels_controller.rb
class PixelsController < ApplicationController
  before_action :enforce_current_user

  def create_bulk
    red = params[:color][0]
    green = params[:color][1]
    blue = params[:color][2]

    params[:range].each do |x,y|
      Pixel.create(
        user_id: current_user.id,
        red: red,
        green: green,
        blue: blue,
        x: x,
        y: y,
      )
    end
  end

  private

  def enforce_current_user
    if current_user.blank?
      redirect_to new_session_path
    end
  end
end

backend/app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
  end

  def create
    user = User.new(username: params[:registration][:username])

    create_options = WebAuthn::Credential.options_for_create(
      user: {
        name: params[:registration][:username],
        id: user.webauthn_id
      },
      authenticator_selection: { user_verification: "required" }
    )

    if user.valid?
      session[:current_registration] = { challenge: create_options.challenge, user_attributes: user.attributes }

      respond_to do |format|
        format.json { render json: create_options }
      end
    else
      respond_to do |format|
        format.json { render json: { errors: user.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def callback
    webauthn_credential = WebAuthn::Credential.from_create(params)

    user = User.create!(session["current_registration"]["user_attributes"])

    begin
      webauthn_credential.verify(session["current_registration"]["challenge"], user_verification: true)

      credential = user.credentials.build(
        external_id: Base64.strict_encode64(webauthn_credential.raw_id),
        nickname: params[:credential_nickname],
        public_key: webauthn_credential.public_key,
        sign_count: webauthn_credential.sign_count
      )

      if credential.save
        sign_in(user)

        render json: { status: "ok" }, status: :ok
      else
        render json: "Couldn't register your Security Key", status: :unprocessable_entity
      end
    rescue WebAuthn::Error => e
      render json: "Verification failed: #{e.message}", status: :unprocessable_entity
    ensure
      session.delete("current_registration")
    end
  end
end

backend/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: session_params[:username])

    if user
      get_options = WebAuthn::Credential.options_for_get(
        allow: user.credentials.pluck(:external_id),
        user_verification: "required"
      )

      session[:current_authentication] = { challenge: get_options.challenge, username: session_params[:username] }

      respond_to do |format|
        format.json { render json: get_options }
      end
    else
      respond_to do |format|
        format.json { render json: { errors: ["Username doesn't exist"] }, status: :unprocessable_entity }
      end
    end
  end

  def callback
    webauthn_credential = WebAuthn::Credential.from_get(params)

    user = User.find_by(username: session["current_authentication"]["username"])

    raise "user #{session["current_authentication"]["username"]} never initiated sign up" unless user

    credential = user.credentials.find_by(external_id: Base64.strict_encode64(webauthn_credential.raw_id))

    begin
      webauthn_credential.verify(
        session["current_authentication"]["challenge"],
        public_key: credential.public_key,
        sign_count: credential.sign_count,
        user_verification: true
      )

      credential.update!(sign_count: webauthn_credential.sign_count)
      sign_in(user)

      render json: { status: "ok" }, status: :ok
    rescue WebAuthn::Error => e
      render json: "Verification failed: #{e.message}", status: :unprocessable_entity
    ensure
      session.delete("current_authentication")
    end
  end

  def destroy
    sign_out

    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username)
  end
end

backend/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

backend/app/helpers/pixels_helper.rb
module PixelsHelper
end

backend/app/views/application/_feature_detection.html.erb
<div class="mdc-list hidden" data-controller="feature-detection">
  <div class="mdc-list-item">
    <span class="mdc-list-item__graphic material-icons">warning</span>
    <span class="mdc-list-item__text">
      <span class="mdc-typography--body2" data-target="feature-detection.message">
      </span>
    </span>
  </div>
</div>

backend/app/views/home/index.html.erb
<div class="mdc-list-group">
  <h3 class="mdc-list-group__subheader">Your Security Keys</h3>
  <ul class="mdc-list mdc-list--two-line">
    <% current_user.credentials.each do |credential| %>
      <li class="mdc-list-item">
        <span class="mdc-list-item__graphic material-icons">vpn_key</span>

        <span class="mdc-list-item__text">
          <span class="mdc-list-item__primary-text">
            <%= credential.nickname %>
          </span>

          <span class="mdc-list-item__secondary-text">
            <%= credential.external_id %>
          </span>
        </span>

        <% if current_user.can_delete_credentials? %>
          <%= link_to "delete", credential, method: :delete, class: "mdc-list-item__meta material-icons" %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div data-controller="add-credential">
    <%= form_with scope: :credential, url: credentials_path, remote: true, data: { action: "ajax:success->add-credential#create" } do |form| %>
      <div class="form-field">
        <div class="mdc-text-field mdc-text-field--fullwidth" data-controller="textfield">
          <%= form.text_field :nickname, class: "mdc-text-field__input", placeholder: "New Security Key nickname", required: true %>
          <div class="mdc-line-ripple"></div>
        </div>
      </div>

      <div class="center">
        <%= form.submit "Add Security Key", class: "mdc-button mdc-button--unelevated" %>
      </div>
    <% end %>
  </div>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixel Rush</title>
    <meta name="description" content="Claim some pixels with passwordless auth">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <% if Rails.env.test? %>
      <%= javascript_pack_tag 'stub_credentials', 'data-turbolinks-track': 'reload' %>
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mdc-theme--background mdc-typography">
    <header class="mdc-top-app-bar">
      <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
          <span class="mdc-top-app-bar__title">Pixel Rush</span>
        </section>

        <% if current_user %>
          <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">

            <div class="mdc-menu-surface--anchor" data-controller="menu">
              <button class="material-icons mdc-top-app-bar__action-item mdc-icon-button" data-action="menu#open">account_circle</button>

              <div class="mdc-menu mdc-menu-surface" tabindex="-1" data-target="menu.openable">
                <div class="mdc-list">
                  <div class="mdc-list-item">
                    <span class="mdc-list-item__text">
                      <%= current_user.username %>
                    </span>
                  </div>

                  <div role="separator" class="mdc-list-divider"></div>

                  <%= link_to session_path, class: "mdc-list-item", method: :delete do %>
                    <span class="mdc-list-item__graphic material-icons">launch</span>
                    <span class="mdc-list-item__text">
                      Sign out
                    </span>
                  <% end %>
                </div>
              </div>
            </div>
          </section>
        <% end %>
      </div>
    </header>

    <div class="content mdc-top-app-bar--fixed-adjust">
      <div class="page-content">
        <%= yield %>
      </div>
    </div>

    <div class="mdc-snackbar js-messenger">
      <div class="mdc-snackbar__surface">
        <div class="mdc-snackbar__label" role="status" aria-live="polite">
        </div>

        <div class="mdc-snackbar__actions">
          <button type="button" title="dismiss" class="mdc-icon-button material-icons mdc-snackbar__dismiss">close</button>
        </div>
      </div>
    </div>
  </body>
</html>